### ISSUE TITLE
v0.2.3 breaks x86_64 compatibility on mac

### ISSUE THREAD

**Issue by itsmichaelyu** [Boomaa23/open-ds#11]
On 0.2.3 I get the error of 
`Exception in thread "main" com.boomaa.opends.util.NativeSystemError: Unsupported architecture x86_64
	at com.boomaa.opends.util.Architecture.getCurrent(Architecture.java:14)
	at com.boomaa.opends.util.Libraries.init(Libraries.java:22)
	at com.boomaa.opends.display.DisplayEndpoint.main(DisplayEndpoint.java:135)
`
But I can launch the 0.2.2 version. I am on a intel mac, so I would suspect the M1 mac change is breaking something.

**Comment by Boomaa23** [comment]
Will fix. Thanks for bringing this to my attention.

**Comment by Boomaa23** [comment]
Please let me know if this works: 
[open-ds-v0.2.3-jar-with-dependencies.zip](https://github.com/Boomaa23/open-ds/files/8238890/open-ds-v0.2.3-jar-with-dependencies.zip)

**Comment by itsmichaelyu** [comment]
It does work

**Comment by Boomaa23** [comment]
Ok great, I will update.

**Comment by Boomaa23** [comment]
Fixed by 1f99934402e2bcd34afc3b8f9963b5f11da5ebde
