### ISSUE TITLE
GUI Improvement: merge with qdriverstation ?

### ISSUE THREAD

**Issue by TrevCan** [Boomaa23/open-ds#7]
Hello, first of all thank you for making this! 

I don't know if it's my computer, but how is the UI supposed to look? 

![image](https://user-images.githubusercontent.com/44383325/149239862-53a11837-a1bb-4ed6-ac99-283ef3497e24.png)

I haven't tested your driver station yet, but it seems promising. I would recommend maybe merging the 'GUI' aspect of the project with 
[QDriver](https://github.com/FRC-Utilities/QDriverStation), which, in my opinion, has a significantly better GUI. Althought the code itself hasn't been updated to work with the new protocols.

I'd also appreciate very much if you could share your findings on the FRC Driver station protocol.

Thank you.

**Comment by Boomaa23** [comment]
Hey! I actually wrote up the 2020 protocol for LibDS (which is the communication for QDriverStation) and it had some issues. I admit the GUI on this isn't great but it works and has every feature necessary. 

The protocol is hidden in the code but if I get some more time I'll make a writeup. You should be able to resize the GUI as well.

Thanks!

**Comment by Boomaa23** [comment]
I was going to ask if the GUI started at that size but I see you're using a WM in some Linux env, so it probably auto-fullscreened!
