### ISSUE TITLE
Add 'offline' mode when connected to robot network.

### ISSUE THREAD

**Issue by TrevCan** [Boomaa23/open-ds#8]
If you're connected to the modem in the roboRIO, it'd be nice to be in an offline mode **when running the run-opends.sh script** where it doesn't complain if I don't have internet. 

I'll try to work on a patch to fix this.

As of now, I get:

```
> ./run-opends.sh
No open-ds-.jar detected. Downloading latest release from GitHub.
curl: no URL specified!
curl: try 'curl --help' for more information
Java installation detected on PATH. Running OpenDS...

Error: Invalid or corrupt jarfile open-ds-.jar
```
which clearly exits with an error.

**Comment by Boomaa23** [comment]
Good catch. I'll work on it.

**Comment by TrevCan** [comment]
Sorry to add so many issues btw, but I think there's a bug that sometimes happens and is most likely related to this one. 

Whenever the driver station temporarily disconnects, I think the java code hangs at an exception that says something like `could not connect to github.com` and may be the culprit of it sometimes not working.

**Comment by Boomaa23** [comment]
Ah that's okay! I believe these are separate issues as the first one has to do with the launcher script and the second is the app code itself. That error is likely the same as here: https://github.com/Boomaa23/open-ds/issues/6#issuecomment-1011554861 and it should be fixed in the next version binary (or it is already fixed if you can compile from source).

**Comment by TrevCan** [comment]
Great. thanks.

**Comment by Boomaa23** [comment]
Alright @TrevCan I think commit efc44b32d85d0ecc51dd3567f9f0c94819eaf2a1 should fix this problem for macOS and Linux. Please re-download and let me know if it does.

**Comment by Boomaa23** [comment]
Commit 4c4b7b3 should also fix this on Windows. Marking this as closed as the feature has been added.
